name: auto deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALI_HOST }}
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}
          script: |
            cd /root/trendFundFed
            yarn build
            cd /root/tgdog.github.io
            scp -r /root/trendFundFed/build/. ./
            git add .
            git commit -m"update"
            git push origin master
